### ISSUE TITLE
Deploy using now-pipeline cannot find files in subfolder

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/todomvc-express#7]
Page at https://todomvc-express-dtrwjilenx.now.sh/ shows

```
Installing package es6-symbol@~3.1
pre-git 3.10.0 in /home/nowuser/src/node_modules/77307dd294b4d8be775930573adba866e0b2e70a
running install inside self, no need
cwd /home/nowuser/src/node_modules/77307dd294b4d8be775930573adba866e0b2e70a
pkgPath node_modules/pre-git
npm start
module.js:442
    throw err;
    ^

Error: Cannot find module './render/render'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nowuser/src/src/index-page.js:1:78)
```

**Comment by bahmutov** [comment]
done
